language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.6
env:
  - IMAGE=centos:7
  - IMAGE=debian:jessie
bundler_args: "--jobs=4"
cache: bundler
before_install: gem install bundler -v 2.0.1
before_script:
  - docker run --privileged -d --name container-with-service $IMAGE /sbin/init
script:
  - bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --container=container-with-service --tag itamae-plugin:latest
  - DOCKER_CONTAINER=container-with-service bundle exec rspec
branches:
  only:
    - master
